name: gwb

channels:
  - astropy

dependencies:
  - python=3
  - astropy
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - h5py
  - pip
  - jupyter
  - pip:
    - six
    - schwimmbad
    - networkx
